# NumPy y la estructura `ndarray` (Arrays N-Dimensionales)

Para el análisis de datos y cálculo numérico en Python, la herramienta estándar de la industria es **NumPy** (Numerical Python). Su núcleo central es un objeto llamado **`ndarray`** (n-dimensional array).

### Diferencias clave entre Listas de Python y `ndarray` de NumPy:
1. **Homogeneidad:** A diferencia de las listas normales de Python (que pueden mezclar textos, números y booleanos), **todos los elementos de un `ndarray` deben ser del mismo tipo** (por ejemplo, todos enteros o todos decimales). Esto los hace increíblemente rápidos y eficientes en memoria.
2. **Atributos matemáticos:** Los arrays tienen conceptos matemáticos integrados:
   * **Rank:** Es el número de dimensiones de la matriz (1D, 2D, 3D...).
   * **Shape:** Es una tupla que indica el tamaño de la matriz en cada dimensión (ej: `(3, 4)` significa 3 filas y 4 columnas).

---

### 1. Importar la librería y crear Arrays básicos

La convención universal es importar numpy con el alias `np`. Usamos `np.array()` pasándole una lista o lista de listas.



In [31]:
import numpy as np

# Array 1D (Vector)
vector_a = np.array([1, 2, 3, 5, 8, 13])
print("Vector 1D:\n", vector_a)

# Array 2D (Matriz) a partir de listas anidadas
matriz_b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("\nMatriz 2D:\n", matriz_b)

# Accediendo a los datos (Indexación base 0)
print("\nPrimer elemento del vector:", vector_a[0])      # Salida: 1
print("Primera fila de la matriz:", matriz_b[0])       # Salida: [1 2 3 4]
print("Elemento específico (Fila 1, Columna 2):", matriz_b[1][2]) # Salida: 7

Vector 1D:
 [ 1  2  3  5  8 13]

Matriz 2D:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Primer elemento del vector: 1
Primera fila de la matriz: [1 2 3 4]
Elemento específico (Fila 1, Columna 2): 7


### La anatomía de un `ndarray`: Punteros y Metadatos

A diferencia de las listas de Python (que guardan referencias esparcidas por toda la memoria), un `ndarray` de NumPy es un bloque de memoria contiguo (un puntero a la memoria) acompañado de **metadatos** que le dicen a Python cómo interpretar esos bytes. 

Estos metadatos principales son:

1. **`dtype` (Data Type):** Es el tipo de dato de la matriz. A diferencia de las listas, **debe ser único** para toda la estructura. Esto garantiza que cada elemento ocupe exactamente el mismo número de bytes en la memoria (ej. `int64` ocupa 8 bytes, `float32` ocupa 4 bytes).
2. **`shape` (Forma):** Es una tupla que indica el número de elementos que hay en cada dimensión de la matriz (ej. `(3, 4)` significa 3 filas por 4 columnas).
3. **`strides` (Pasos):** Es un concepto más avanzado. Indica el número exacto de **bytes** que el ordenador debe saltar en la memoria para pasar de un elemento al siguiente (ya sea avanzando en la misma fila, o saltando a la siguiente columna).

#### Atributos útiles para consultar un array
Si tenemos un array llamado `a`, podemos consultar sus metadatos directamente:
* `a.shape`: Devuelve la tupla con las dimensiones.
* `a.size`: Devuelve el número **total** de elementos (si es de 3x4, devolverá 12).
* `a.dtype`: Devuelve el tipo de dato de sus elementos.

### Otras funciones útiles para crear arrays en NumPy

Además de ceros, unos y matrices vacías, NumPy nos ofrece herramientas muy prácticas para crear matrices con patrones específicos:

* **`np.arange(inicio, fin, salto)`**: Funciona igual que el `range()` nativo de Python, pero devuelve un `ndarray`. Crea una secuencia de números desde el `inicio` hasta el `fin` (sin incluirlo), avanzando según el `salto`. Es ideal combinarlo con el método `.reshape()` para darle forma de matriz.
* **`np.identity(n)`**: Crea y devuelve la **matriz identidad** de dimensión `n`x`n`. (Una matriz cuadrada donde la diagonal principal está llena de unos y el resto son ceros).
* **`np.full(dimensiones, valor)`**: Crea un array con las dimensiones especificadas y lo rellena completamente con el `valor` que le indiques.

In [32]:
import numpy as np

# 1. Creación con np.arange (crea un array del 0 al 11)
# Similar a range(12), pero devuelve un ndarray
test_array = np.arange(12)
print("Array original creado con arange:\n", test_array)

# Cambiamos su forma (shape) a una matriz de 3 filas y 4 columnas
matriz = test_array.reshape((3, 4))
print("\nMatriz tras aplicar reshape(3, 4):\n", matriz)
print("-" * 40)

# 2. Consultando los Atributos
print("Atributo shape (Forma):", matriz.shape) # Salida: (3, 4)
print("Atributo size (Total elementos):", matriz.size) # Salida: 12
print("Atributo dtype (Tipo de dato):", matriz.dtype)  # Salida: int32 o int64

# 3. Consultando los Strides (Avanzado)
# Nos dice cuántos bytes saltar para cambiar de dimensión
print("Atributo strides (Bytes por salto):", matriz.strides) 
# Si el dtype es int64 (8 bytes por número):
# El resultado será algo como (32, 8). 
# Significa: "Salta 32 bytes para bajar a la siguiente fila, y 8 bytes para ir a la siguiente columna".
# si el datatype es int32 (4 bytes por número), el resultado será algo como (16, 4)
#significa: "Salta 16 bytes para bajar a la siguiente fila, y 4 bytes para ir a la siguiente columna".


Array original creado con arange:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Matriz tras aplicar reshape(3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------------------------
Atributo shape (Forma): (3, 4)
Atributo size (Total elementos): 12
Atributo dtype (Tipo de dato): int32
Atributo strides (Bytes por salto): (16, 4)


In [33]:
import numpy as np

matrizA = np.identity(3) # Crea una matriz identidad de 3x3
print("Matriz A (Identidad 3x3):\n", matrizA)
matrizB = np.full((3, 3), 7) # Crea una matriz de 3x3 llena de 7
print("\nMatriz B (Llena de 7):\n", matrizB)

Matriz A (Identidad 3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz B (Llena de 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


### Creación rápida de arrays especiales en NumPy

NumPy proporciona funciones integradas para crear matrices sin necesidad de introducir los datos manualmente o usar bucles. Las tres más comunes son:

* **`np.zeros(shape)`**: Crea un array del tamaño especificado relleno completamente con ceros (`0`). Es muy útil para inicializar matrices que luego vamos a ir llenando con cálculos (como contadores o acumuladores).
* **`np.ones(shape)`**: Funciona exactamente igual que `zeros`, pero rellena la matriz con unos (`1`).
* **`np.empty(shape)`**: Crea un array sin inicializar sus valores. En lugar de llenarlo con ceros o unos, simplemente reserva el bloque de memoria necesario. **Ojo:** Los valores que aparecen dentro son "basura" (datos residuales que estaban previamente en esa parte de la memoria RAM). Es ligeramente más rápida que `zeros` o `ones`, ideal si vas a sobrescribir absolutamente todos los valores inmediatamente después.

> **Nota:** Por defecto, estas tres funciones crean arrays con datos de tipo decimal flotante (`float64`).

In [34]:
import numpy as np

# 1. np.zeros: Matriz de 2 filas y 3 columnas llena de ceros
matriz_ceros = np.zeros((2, 3))
print("np.zeros((2, 3)):\n", matriz_ceros)
print("-" * 30)

# 2. np.ones: Vector de 4 elementos lleno de unos
vector_unos = np.ones(4)
print("np.ones(4):\n", vector_unos)
print("-" * 30)

# 3. np.empty: Matriz 2x2 vacía (mostrará basura de la memoria)
matriz_vacia = np.empty((2, 2))
print("np.empty((2, 2)):\n", matriz_vacia)

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
np.ones(4):
 [1. 1. 1. 1.]
------------------------------
np.empty((2, 2)):
 [[1. 1.]
 [1. 1.]]


### Operaciones Vectorizadas sobre Arrays

Si intentas hacer `[1, 2, 3] + 1` con una lista nativa de Python, dará error. Si haces `[1, 2] + [3, 4]`, Python simplemente las junta: `[1, 2, 3, 4]`. 

NumPy cambia estas reglas. Las operaciones aritméticas en NumPy se realizan **uno a uno (element-wise)**. Esto se conoce como **vectorización** y es lo que hace que NumPy sea tan rápido, ya que las operaciones se ejecutan a bajo nivel en C.

1. **Operaciones con Escalares:** Si sumas, restas, multiplicas o divides un array por un número (escalar), la operación se aplica a **cada uno de los elementos** de la matriz.
2. **Operaciones entre Arrays:** Si operas dos arrays de las mismas dimensiones, la operación se aplica **posición por posición** (el elemento 0 con el 0, el 1 con el 1, etc.).

In [35]:
import numpy as np

a = np.arange(5)  # Crea el vector: [0, 1, 2, 3, 4]
print("Vector original 'a':", a)

# 1. Operación Escalar (Vector + Número)
print("a + 10  ->", a + 10)  
print("a * 2   ->", a * 2)   

# 2. Operación entre Vectores (Vector + Vector)
# Generamos otro vector con números aleatorios para probar
np.random.seed(0) # Fijamos semilla para que siempre salgan los mismos números
x = np.array(np.random.rand(5) * 10) #np.random.rand(5) genera 5 números aleatorios entre 0 y 1, luego los multiplicamos por 10 para escalarlos a un rango de 0 a 10

print("\nVector aleatorio 'x':", x)
print("a + x   ->", a + x)  # Suma posición a posición

Vector original 'a': [0 1 2 3 4]
a + 10  -> [10 11 12 13 14]
a * 2   -> [0 2 4 6 8]

Vector aleatorio 'x': [5.48813504 7.15189366 6.02763376 5.44883183 4.23654799]
a + x   -> [5.48813504 8.15189366 8.02763376 8.44883183 8.23654799]


### Slicing: Extrayendo subvectores y submatrices

Al igual que en las listas nativas de Python, en NumPy podemos usar el operador `:` para extraer porciones de un array (slicing). La sintaxis general es `[inicio:fin:paso]`.

La verdadera magia ocurre en matrices multidimensionales (2D o más), ya que **podemos hacer slicing en cada dimensión separándola por comas**: `matriz[filas, columnas]`.

* `matriz[0, :]`: Extrae la fila 0 completa.
* `matriz[:, 1]`: Extrae la columna 1 completa.
* `matriz[0:2, 1:3]`: Extrae una submatriz (intersección de las filas 0 y 1, con las columnas 1 y 2).

### Filtrado de datos (Boolean Masking)

Una de las características más potentes de NumPy es la capacidad de filtrar datos usando condiciones lógicas de forma directa, sin usar bucles `if`.

Si le aplicamos una condición a un array (ej. `a > 2`), NumPy devuelve una "máscara" de Verdaderos y Falsos. Si pasamos esa máscara dentro de los corchetes `a[condicion]`, NumPy **devuelve un nuevo array 1D** que contiene únicamente los elementos que cumplen la condición (los que eran `True`).

In [36]:
import numpy as np 

# Crear una matriz de 4 filas y 5 columnas con números del 0 al 19
matriz = np.arange(20).reshape((4, 5))
print("Matriz original:\n", matriz)
# Extraer la segunda fila (index 1)
fila_1 = matriz[1, :] # El ":" indica que queremos todas las columnas de esa fila
print("\nSegunda fila (index 1):", fila_1)
# Extraer la tercera columna (index 2)
columna_2 = matriz[:, 2] # El ":" indica que queremos todas las filas de esa columna
print("\nTercera columna (index 2):", columna_2)
# Extraer una submatriz de las filas 1 a 2 (index 1 a 2) y columnas 2 a 3 (index 2 a 3)
submatriz = matriz[1:3, 2:4] # El rango 1:3 incluye las filas 1 y 2, el rango 2:4 incluye las columnas 2 y 3
print("\nSubmatriz (filas 1-2, columnas 2-3):\n", submatriz)


# Crear un vector de números del 0 al 9
vector = np.arange(10)
print("Vector original:", vector)
# Crear una máscara booleana para filtrar los números pares
mascara_pares = (vector % 2 == 0) # Esto devuelve un array de True/False donde True indica que el número es par
print("Máscara booleana para números pares:", mascara_pares)
# Usar la máscara para extraer solo los números pares del vector
numeros_pares = vector[mascara_pares]
print("Números pares extraídos:", numeros_pares)

Matriz original:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Segunda fila (index 1): [5 6 7 8 9]

Tercera columna (index 2): [ 2  7 12 17]

Submatriz (filas 1-2, columnas 2-3):
 [[ 7  8]
 [12 13]]
Vector original: [0 1 2 3 4 5 6 7 8 9]
Máscara booleana para números pares: [ True False  True False  True False  True False  True False]
Números pares extraídos: [0 2 4 6 8]


### Álgebra Lineal: Producto Matricial y Traspuesta

En NumPy, el operador `*` multiplica matrices **elemento a elemento** (posición por posición). Sin embargo, en matemáticas y Machine Learning, a menudo necesitamos hacer el **producto matricial** real (multiplicar filas por columnas). 

Para esto usamos:
* **`a.dot(b)`** o el operador **`@`**: Realiza el producto matricial. (Las dimensiones internas deben coincidir, ej. una matriz 2x3 multiplicada por una de 3x2).
* **`a.T`**: Devuelve la matriz traspuesta (intercambia filas por columnas).

### Álgebra Lineal Avanzada: El submódulo `numpy.linalg`

Aunque ya vimos el producto matricial (`@` o `.dot()`) y la matriz traspuesta (`.T`), NumPy tiene un submódulo específico llamado `linalg` (Linear Algebra) que contiene funciones matemáticas mucho más avanzadas para trabajar con matrices cuadradas.

Las operaciones más fundamentales que debes conocer son:

* **`np.linalg.det(A)` (Determinante):** Calcula el determinante de una matriz cuadrada. Es un valor escalar que nos dice, entre otras cosas, si la matriz tiene inversa (si el determinante es distinto de cero).
* **`np.linalg.inv(A)` (Inversa):** Calcula la matriz inversa. Es aquella matriz que, al multiplicarse por la original, da como resultado la Matriz Identidad.
* **`np.linalg.solve(A, B)` (Resolver sistemas de ecuaciones):** Permite resolver sistemas de ecuaciones lineales del tipo `Ax = B`, donde `A` es la matriz de coeficientes y `B` es el vector de resultados.



In [37]:

import numpy as np

# Crear una matriz de 3x3
matriz = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 9]])

# Calcular la transpuesta de la matriz
transpuesta = matriz.T
print("Matriz original:\n", matriz)
print("matriz  transpuesta:\n",transpuesta)

matrizdeterminante = np.linalg.det(matriz)
print(matrizdeterminante)

solucion = np.linalg.solve(matriz, np.array([2,3,4]))
print(solucion)

matrizb = np.array([[3, 4, 5], [6,7, 8], [9, 10, 11]])

multiplicacion = matriz.dot(matrizb)
print("multiplicación de matrices:\n",multiplicacion)



Matriz original:
 [[1 2 3]
 [4 5 6]
 [5 6 9]]
matriz  transpuesta:
 [[1 4 5]
 [2 5 6]
 [3 6 9]]
-5.999999999999995
[-1.          1.          0.33333333]
multiplicación de matrices:
 [[ 42  48  54]
 [ 96 111 126]
 [132 152 172]]


### Funciones Universales (ufuncs) y el concepto de `axis` (Ejes)

Para finalizar los fundamentos de NumPy, es vital conocer sus funciones de agregación estadísticas (`sum`, `mean`, `max`, `min`). 

Por defecto, si llamas a `matriz.sum()`, sumará **absolutamente todos** los números de la matriz. Pero normalmente queremos sumar por columnas o por filas. Para eso sirve el parámetro **`axis`**:

* **`axis=0`**: Aplica la operación a lo largo del eje 0 (hacia abajo). Es decir, comprime las filas, resultando en operaciones **por columnas**.
* **`axis=1`**: Aplica la operación a lo largo del eje 1 (hacia la derecha). Es decir, comprime las columnas, resultando en operaciones **por filas**

### Operaciones Estadísticas y Posicionales

NumPy incluye un conjunto completo de funciones para estadística descriptiva. Al igual que con las sumas, puedes aplicar estas funciones a toda la matriz completa o por ejes usando `axis=0` (columnas) o `axis=1` (filas).

Las funciones estadísticas fundamentales son:
* **`mean()`**: Calcula la media (promedio) aritmética.
* **`np.median(array)`**: Calcula la mediana (el valor central). *Ojo: a diferencia de las otras, se suele llamar desde la librería `np` pasándole el array.*
* **`std()`**: Calcula la desviación estándar (qué tan dispersos están los datos).
* **`var()`**: Calcula la varianza (el cuadrado de la desviación estándar).

#### Funciones posicionales (`argmin` y `argmax`)
A veces no nos interesa saber *cuál* es el valor máximo o mínimo, sino **en qué posición (índice)** se encuentra. Para eso usamos:
* **`argmax()`**: Devuelve el índice donde se encuentra el valor máximo.
* **`argmin()`**: Devuelve el índice donde se encuentra el valor mínimo..

In [38]:
import numpy as np

datos = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Matriz de datos:\n", datos)
print("-" * 30)

# 1. Agregación global (todo el array)
print("Suma total:", datos.sum())
print("Valor máximo de toda la matriz:", datos.max())
print("-" * 30)

# 2. Agregación por Ejes (Axis)
print("Suma por columnas (axis=0):", datos.sum(axis=0)) # Resultado: [5, 7, 9]
print("Suma por filas (axis=1):", datos.sum(axis=1))    # Resultado: [6, 15]

# Calcular el promedio por columnas
print("Promedio por columnas:", datos.mean(axis=0))

# Imaginemos las calificaciones de 3 estudiantes en 4 exámenes
calificaciones = np.array([
    [7.5, 8.0, 9.0, 6.5], # Estudiante 1
    [5.0, 6.5, 7.0, 5.5], # Estudiante 2
    [9.5, 10.0, 9.5, 9.0] # Estudiante 3
])

print("Matriz de calificaciones:\n", calificaciones)
print("-" * 40)

# 1. Estadísticas Globales (de toda la clase)
print("Promedio de toda la clase:", calificaciones.mean())
print("Mediana de toda la clase:", np.median(calificaciones))
print("Desviación estándar global:", calificaciones.std())
print("-" * 40)

# 2. Estadísticas por Eje (Axis)
# Promedio de cada estudiante (comprimimos las columnas -> axis=1)
promedios_estudiantes = calificaciones.mean(axis=1)
print("Promedio por estudiante (axis=1):", promedios_estudiantes)

# Promedio de cada examen (comprimimos las filas -> axis=0)
promedios_examenes = calificaciones.mean(axis=0)
print("Promedio por examen (axis=0):", promedios_examenes)
print("-" * 40)

# 3. Argmax y Argmin (Posiciones)
vector_edades = np.array([22, 18, 35, 29, 40, 19])
print("Vector edades:", vector_edades)

indice_max = vector_edades.argmax()
indice_min = vector_edades.argmin()

print(f"La persona más mayor tiene {vector_edades[indice_max]} años y está en el índice [{indice_max}]")
print(f"La persona más joven tiene {vector_edades[indice_min]} años y está en el índice [{indice_min}]")

Matriz de datos:
 [[1 2 3]
 [4 5 6]]
------------------------------
Suma total: 21
Valor máximo de toda la matriz: 6
------------------------------
Suma por columnas (axis=0): [5 7 9]
Suma por filas (axis=1): [ 6 15]
Promedio por columnas: [2.5 3.5 4.5]
Matriz de calificaciones:
 [[ 7.5  8.   9.   6.5]
 [ 5.   6.5  7.   5.5]
 [ 9.5 10.   9.5  9. ]]
----------------------------------------
Promedio de toda la clase: 7.75
Mediana de toda la clase: 7.75
Desviación estándar global: 1.6007810593582121
----------------------------------------
Promedio por estudiante (axis=1): [7.75 6.   9.5 ]
Promedio por examen (axis=0): [7.33333333 8.16666667 8.5        7.        ]
----------------------------------------
Vector edades: [22 18 35 29 40 19]
La persona más mayor tiene 40 años y está en el índice [4]
La persona más joven tiene 18 años y está en el índice [1]
